### ISSUE TITLE
Set viewport on drawing board

### ISSUE THREAD

**Issue by ppeeou** [yorkie-team/codepair#115]
**Description**:

Codepair is displaying the coordinates of the screen as absolute values

We need to show dots on the screen according to the viewport.

**Why**:

All recorded dots must be displayed on the mobile environment and on screens with different resolution

If the resolution is different, the recorded point may not be visible.
![image](https://user-images.githubusercontent.com/10924072/119216660-e244df00-bb0f-11eb-8ae4-0b64c759e7e3.png)

**Comment by easylogic** [comment]
Close the issue because it supports tldraw.
