### ISSUE TITLE
Bump up the chokidar package, or change package manager.

### ISSUE THREAD

**Issue by SimYunSup** [yorkie-team/codepair#136]
**Description**:
![image](https://user-images.githubusercontent.com/47362439/131218574-f3efa295-2631-4d1e-bba7-07810827e81c.png)
We need to run `npm update --package-lock chokidar`or Change package manager to yarn(for [lock file consistency](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion)).

If we change package manager to yarn, We need to change the [code](https://github.com/yorkie-team/yorkie-codepair/blob/1ad33d0f1f73b541b3a1cbff5428093d915e05a7/webapp/src/components/Editor/Editor.tsx#L39) like [example](https://material-ui.com/styles/api/#examples-3).

**Why**:
Because up to node 14+, `chokidar@2` doesn't work [related issue](https://github.com/facebook/create-react-app/issues/10811).

**Comment by ppeeou** [comment]
@SimYunSup 

For the lock version, I thought it would be fine to use npm+7. (npm 6 already legacy)
![image](https://user-images.githubusercontent.com/10924072/131253897-46832d07-7d61-4766-93ae-80ff9ba5b3d4.png)

Is it common to use yarn for "lock file consistency" feature??

**Comment by SimYunSup** [comment]
I think using yarn is common to save consistency lock file because create-react-app

**Comment by SimYunSup** [comment]
@ppeeou npm 6 is legacy now, but if someone use node 14, they can't work well in this repository. Because node 14 doesn't include npm 7.
![image](https://user-images.githubusercontent.com/47362439/131257121-245c7417-ccfb-419f-a4e6-b2e2d6d013c1.png)

**Comment by ppeeou** [comment]
I am not familiar with yarn

But if we use it, we should also maintain package-lock.json.
https://blog.npmjs.org/post/621733939456933888/npm-v7-series-why-keep-package-lockjson

Could you please post a PR for this issue??

**Comment by SimYunSup** [comment]
I will make PR with yarn lock file as soon as possible, but It will be made at afternoon.

**Comment by hackerwins** [comment]
There seems to be no problem now. If the problem recurs, please reopen it.
