### ISSUE TITLE
Display names of all participants when showing presence with 4 or more members

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#139]
**What would you like to be added**:
Currently, when displaying presence with 4 or more members, only a summary such as "+3" is shown, which doesn't allow users to see the names of all participants. I would like to enhance this behavior so that the names of all participants can be displayed.

**Why is this needed**:
With a large number of participants, it is important to be able to easily identify all the members present. This enhancement will improve the usability and user experience of the presence feature.

**Additional context**:

**Comment by KimKyuHoi** [comment]
it's interesting issue? Could I give it a try?

**Comment by devleejb** [comment]
@KimKyuHoi 
Sure! Sorry for late response.
