### ISSUE TITLE
Sync vertical scrolling between Markdown editor and viewer

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#140]
**What would you like to be added**:
In the Markdown editor and viewer mode, when working with a split-screen layout where the left side is the Markdown editor and the right side is the Markdown viewer, it would be beneficial to synchronize the vertical scroll between the two panels. This means that when scrolling vertically in either the editor or the viewer, the other panel should also scroll in sync to maintain consistent visibility and context.

**Why is this needed**:
Currently, when editing Markdown and viewing the corresponding rendered output, users may need to scroll vertically separately in the editor and viewer panels. This can be inconvenient and disrupt the viewing experience, especially when navigating through lengthy documents. By implementing this enhancement, users will be able to seamlessly scroll through the content in both panels, improving overall navigation and readability.:

**Additional Information**:

**Comment by devleejb** [comment]
We have used a method that calculates and synchronizes the scroll percentage vertically, but it doesn't seem like a good approach. We need a different, new approach.

**Comment by hackerwins** [comment]
@easylogic Do you have any idea about this problem?

**Comment by easylogic** [comment]
When creating a markdown viewer, create an element by entering an id for each element. 

If you find the element that appears at the top of the screen in the markdown editor and scroll to find the ID of the element in the viewer on the right.
