### ISSUE TITLE
Add functionality to modify document titles

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#143]
**What would you like to be added**:
I would like to request the addition of a feature that allows users to modify the titles of documents in the system. Presently, there is no built-in functionality to change document titles once they are created. 

**Why is this needed**:
The ability to modify document titles is crucial for managing and organizing content effectively. Users may mistakenly enter incorrect or outdated titles when creating documents, and it can be inconvenient or confusing to have no option to correct them. Allowing users to modify document titles will greatly enhance the usability and flexibility of the system.

**Additional Information**:
It is important to ensure that the modification of document titles does not affect the integrity and referential integrity of the system. The changes should be accurately reflected in all relevant parts of the application, including search results, document listings, and any other areas where document titles are displayed.

**Comment by rappire** [comment]
I'm not good at nest and react, but I want to try it because it's a feature I want.
can I work for it?

**Comment by devleejb** [comment]
@rappire
Sure! If you have any questions, feel free to ask.
For now, the design issue isn't important.
However, please note that we're planning to rename the document title like this: [Figma](https://www.figma.com/design/OYc1Cr0nvFuBnWZxhscfDk/Code-Pair?node-id=325-24655&t=v6XTODZsnE3cdV5d-1).

**Comment by devleejb** [comment]
For now, there's no need to notify the changing of document title to other peers.
We can introduce this feature after resolving this issue: https://github.com/yorkie-team/yorkie/issues/628

**Comment by devleejb** [comment]
@rappire Could you share your progress? If there are any issues, I can help.

**Comment by rappire** [comment]
I had some work this week, so I haven't been able to proceed much. Currently, I'm looking at the backend code! If I have any questions, I'll ask right away. Thank you.

**Comment by hugosandsjo** [comment]
Is it possible for me to take this issue or are you still working on it @rappire ?

**Comment by rappire** [comment]
I'm working on this, but I've been busy recently, so it's okay for you to proceed. @hugosandsjo

**Comment by hugosandsjo** [comment]
@rappire ive also been tasked with another issue at the moment but il write again if i start working on this.

**Comment by hugosandsjo** [comment]
@rappire I continued working on this issue and just made a pull request. Just wanted to let you know!
