### ISSUE TITLE
Implement a list of recently edited documents

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#146]
**Description**:

Implement a list of recently edited documents.

Google Drive exposes a list of documents as follows:
<img width="1084" alt="Screen Shot 2021-10-16 at 1 52 01 PM" src="https://user-images.githubusercontent.com/2059311/137574196-dfe7e9af-8362-4a74-9924-fed3923b18e0.png">

**Why**:

It is difficult to remember the URLs of documents that the user has recently modified. Providing a list makes it easy to access again.

**Comment by easylogic** [comment]
Recently viewed articles list added.
