### ISSUE TITLE
Make Vim command input pretty

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#148]
**Description**:

Make Vim command input pretty.

We provide Vim mode using [CodeMirror's vim binding](https://codemirror.net/demo/vim.html).
<img width="609" alt="Screen Shot 2021-10-21 at 3 48 05 PM" src="https://user-images.githubusercontent.com/2059311/138225852-92cc9eef-dfc3-49c4-ae82-b8fcc48644bf.png">

When we type `:`, Command Input appears, but it doesn't come out as pretty as the one below.
<img width="775" alt="Screen Shot 2021-10-21 at 3 48 41 PM" src="https://user-images.githubusercontent.com/2059311/138225897-7bd8b289-b422-45f5-bc0e-63da705bfa0d.png">

**Why**:

- CodePair will get better.

**Comment by eddie0329** [comment]
Hello @hackerwins. I worked on this issue like below:

|Before|After|
|:-------:|:-------:|
|![스크린샷 2022-01-24 오후 12 08 54](https://user-images.githubusercontent.com/40482274/150715805-0f037c23-21f6-414f-a58d-6dd8af52324d.png)|![스크린샷 2022-01-24 오후 12 08 00](https://user-images.githubusercontent.com/40482274/150715724-d37831a1-f633-4c92-a6a5-fae9d109ff22.png)|

If it looks ok, I will open PR!

Thank you. And have a nice day.

**Comment by hackerwins** [comment]
@eddie0329 Thanks for the experiment. It looks better than before. Could you create a PR for this?

**Comment by eddie0329** [comment]
@hackerwins Thanks for reply! :)

Before creating PR, is there any contirbution guide for `codepair`? 

I can see other contribution guides which were included in other respository within yorkie-team, 
but cannot find in `codepair` repository.

**Comment by hackerwins** [comment]
@eddie0329 I forgot that there is no contribution guide on this repository(Thank you for letting me know).

Please refer to the guide in other repo: https://github.com/yorkie-team/yorkie-js-sdk/blob/main/CONTRIBUTING.md
