### ISSUE TITLE
Anonymous access when accessing shared documents despite being logged in

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#148]
**What happened**:
When accessing a shared document, the user is displayed as anonymous even when they are logged in. The issue can be observed in the following screenshot:
![screenshot](https://github.com/yorkie-team/yorkie/assets/81357083/f6e66432-08c7-4d43-bfe5-9278c7c5656f)

**What you expected to happen**:
The user's login status should be properly recognized and displayed as logged in when accessing shared documents.

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce the issue, follow these steps:
1. Go to a shared document.
2. Log in to the platform.
3. Check the user status, which erroneously displays as anonymous.

**Anything else we need to know?**:
Please ensure that you are logged in before accessing the shared document. This issue may be related to authentication or session management.

**Environment**:
- Operating system: ALL
- Browser and version: ALL
- CodePair version: ALL

**Comment by eastfilmm** [comment]
Can I get this issue?

**Comment by devleejb** [comment]
@eastfilmm 
Sure. Please tell me if you need help.

**Comment by devleejb** [comment]
@eastfilmm Could you share your progress? If there are any issues, I can help.

**Comment by choidabom** [comment]
Can I try this issue?

**Comment by devleejb** [comment]
@choidabom Sure, I'll assign you.
