### ISSUE TITLE
Apply UpdateMetadata to line drawing

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#155]
**Description**:

Apply UpdateMetadata to the line drawing.

When users draw lines, the users start drawing by mouse down, then when mouse up, a line is completed.

1. While drawing a line, use `UpdateMetadata` to send raw points directly to the peers.
2. When the line drawing is completed, sample raw points then add them to the document as a line.
3. When painting lines using points, apply Bezier Curve to the sampled points.

Currently, during line drawing, the line is wobbly because it is painted by sampling points and changing it to a bezier curve.

**Why**:

- We can provide a smoother line drawing experience.

**Comment by easylogic** [comment]
tldraw 를 지원하기 때문에 이슈를 닫습니다.
