### ISSUE TITLE
Anchor the canvas of the drawing to the document rather than the screen.

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#157]
**Description**:

Anchor the canvas of the drawing to the document rather than the screen.

**Why**:

Recently, I opened a CodePair test with a few of my followers on Twitter. For now, even if the screen is scrolled, the shapes are drawn on the screen follow, but users felt awkward about this.

https://codepair.yorkie.dev/3amy7n

```
- 펜으로 그은 거는 화면을 움직여도 어딜 가든 따라오는군요 <- 요것도 버그 리스트에 옮기겠습니다.
```

**Comment by easylogic** [comment]
Close the issue because it supports tldraw.
