### ISSUE TITLE
Add Vim Binding Support for CodePair Using CodeMirror 6

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#158]
**What would you like to be added**:

In the previous version of CodePair, Vim binding was supported, which was a convenient feature for developers familiar with Vim. However, the previous version was implemented using CodeMirror 5 and used a Vim binding plugin.

With the new version of CodePair using CodeMirror 6, it would be beneficial to check if there is a Vim binding plugin available for this version as well. This will allow users who are accustomed to Vim to use the familiar key bindings in CodePair.

**Why is this needed**:

Adding Vim binding support will provide users with a familiar and efficient editing experience, especially for those who are comfortable with Vim. It will enhance the usability and appeal of CodePair to a wider range of developers.

**Additional Information**:

Additionally, we need to decide how to provide a UI for users to change editor settings, including key binding configurations.

**Comment by devleejb** [comment]
It seems that we can use this library to implement it.
https://github.com/replit/codemirror-vim
