### ISSUE TITLE
Display the remote mouse cursors in drawing mode

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#159]
**Description**:

Display the remote mouse cursors in drawing mode. And users can chat from the mouse pointer.

FigJam example:
![Cursor chat in FigJam](https://user-images.githubusercontent.com/2059311/140049072-b3dc8a00-3598-4fcf-b838-b5d960282ded.gif)

**Why**:

- Users can check the peer's mouse position. And they can communicate with others with the mouse pointer.

**Comment by easylogic** [comment]
Close the issue with tldraw support.
