### ISSUE TITLE
Show nameplate of another user when the position of another user's cursor changes

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#163]
**Description**:

It would be nice if the nameplate of another user appear when the position of the cursor changes due to editing or movement.

**Why**:

While writing together, it's hard to know who's editing the content until the user hovers the mouse over the cursor.

**Comment by metleeha** [comment]
Can I try this issue?

**Comment by hackerwins** [comment]
@metleeha Sure.

**Comment by easylogic** [comment]
Cursor name added.
