### ISSUE TITLE
Linearly slowing down if we draw a lot of lines using brush

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#164]
**Description**:

Linearly slowing down if we draw a lot of lines using brush.
When drawing a lot of lines, find the parts that cause speed problems.

<img width="760" alt="Screen Shot 2021-11-26 at 10 38 44 AM" src="https://user-images.githubusercontent.com/2059311/143514130-a244d1cf-e646-4b3f-afe8-939b332cbfa9.png">

**Why**:

- Users can draw many lines comfortably.

**Comment by easylogic** [comment]
Close this issue with tldraw support.
