### ISSUE TITLE
Add Nickname Change Feature

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#178]
**What would you like to be added**:
Currently, our platform lacks the ability for users to change their nicknames once they have created an account. Introducing a nickname change feature would allow users to update their displayed name easily.

**Why is this needed**:
This enhancement would provide users with more control over their profile information and improve the overall user experience on our platform. 

**Additional Information**:

**Comment by devysi0827** [comment]
can i take this issue?

**Comment by devleejb** [comment]
@devysi0827 

Sure.

You can check the design and planning of this feature in the Figma file.
https://www.figma.com/design/OYc1Cr0nvFuBnWZxhscfDk/Code-Pair?node-id=280-29021&t=lIJKIWXdlNf3Qiaa-1

If you have any questions, feel free to ask.
