### ISSUE TITLE
Add Notification when Accessing Pages such as Documents without Permission

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#196]
**What would you like to be added**:
When users attempt to access pages or documents that they do not have permission to view, instead of simply being redirected or receiving an error page, it would be beneficial to add a notification to inform them of the reason why they cannot access the content. This will provide better user experience and clarity regarding access restrictions.

**Why is this needed**:
Enhancing the feedback provided to users when they encounter access restrictions will improve user experience and help users understand why they cannot view certain pages or documents.

**Additional Information**:

**Comment by wet6123** [comment]
I'm interested in this issue. Can I try it?

**Comment by devleejb** [comment]
@wet6123 
Sure. This is a good issue to understand the Error Handling code of CodePair. If necessary, a simple code modification on the back-end might be required. Is that okay with you?

Please feel free to ask if you have any questions.

**Comment by wet6123** [comment]
@devleejb 
Oh accidentally commented on the wrong issue. Let me see if i can handle it. If it's not possible, I'll notice you.

**Comment by devleejb** [comment]
@wet6123 
OK. If you want to resolve other issue, please tell me.
