### ISSUE TITLE
Error occurs when inputting certain equation syntax causing access issue

### ISSUE THREAD

**Issue by raararaara** [yorkie-team/codepair#200]
**What happened**:
When inputting the following equation syntax without enclosing it in a code block, an error occurs and the document becomes inaccessible.

```plaintext
$\begin\ca$
```

The error message "Something went wrong" is displayed, preventing access to the document.

**What you expected to happen**:
The equation syntax should be correctly processed without causing any access issues.

**How to reproduce it (as minimally and precisely as possible)**:
You can check the case of documents that are inaccessible at [this link](https://codepair.yorkie.dev/raararaara/6660482a1f519c6e71de6adb/share?token=i64pun).

1. Open a document.
2. Input the equation syntax `$\begin\ca$` without using a code block.

**Anything else we need to know?**:
This issue seems to be related to how the equation syntax is interpreted and processed. Steps to reproduce the issue have been provided above.

**Environment**:
- Operating system:
- Browser and version:
- CodePair version:

**Comment by devleejb** [comment]
Related to https://github.com/remarkjs/react-markdown/issues/853.
