### ISSUE TITLE
Remove Global Scroll on Document Edit Page

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#201]
**What would you like to be added**:
On the document edit page, the global scroll should not be visible. Currently, due to unknown margins outside the document, the global scroll is visible.

**Why is this needed**:
To provide a cleaner look and better user experience on the document edit page.

**Additional Information**:

**Comment by bishoe01** [comment]
I'd like to work on this issue, can I take it on?

**Comment by devleejb** [comment]
@bishoe01 
Sure. If you have any questions, feel free to ask.

**Comment by devleejb** [comment]
@bishoe01 
This is more detail description about this issue.

https://github.com/user-attachments/assets/cbc39586-1b87-4f07-9805-37375cbb51e6

As you can see, an unintended space appears at the bottom of the screen, causing a global scroll to occur.
You can check this CodePair document [here](https://codepair.yorkie.dev/devleejb/65c0741d08ff464118584789/share?token=jf0bhn).

If you have any questions, please leave a comment on this GitHub Issue.
