### ISSUE TITLE
Indentation Changes when Dragging Content in the Editor

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#205]
**What happened**:
When dragging content in the editor, there is a noticeable issue where the indentation of the text changes unexpectedly. This seems to occur when the Yorkie Intelligence button is rendered, suggesting that it may be impacting the layout.

**What you expected to happen**:
Content should remain consistent in terms of indentation while dragging in the editor.

**How to reproduce it (as minimally and precisely as possible)**:
Try dragging content within the editor and observe the changes in indentation. 

**Anything else we need to know?**:

**Environment**: ALL
- Operating system: ALL
- Browser and version: ALL
- CodePair version: ALL

**Comment by bishoe01** [comment]
Can I take on this issue?

**Comment by devleejb** [comment]
@bishoe01 
Sure! If you have any questions, feel free to ask me!

**Comment by devleejb** [comment]
@bishoe01 
This issue might conflict with https://github.com/yorkie-team/codepair/issues/267.
Is there any progress?

**Comment by bishoe01** [comment]
@devleejb  I haven't been able to proceed well in the meantime because I suddenly couldn't afford to participate in another contest. You said there seems to be a conflict with #267, so how should I proceed? I'm so sorry for the late response and the inconvenience.

**Comment by devleejb** [comment]
@bishoe01 
I believe this issue can be resolved in #267. Could you wait for that? I'll notify you once it's done.

**Comment by devleejb** [comment]
This issue is resolved by #267.
