### ISSUE TITLE
Fix type error on TypeScript 4.4+ environment

### ISSUE THREAD

**Issue by blurfx** [yorkie-team/codepair#206]
**Description**:
Note) This issue came from Issue #196 and PR #201

Some DOM-related types are has changed since TypeScript 4.4 and TypeScript libdom changes (See https://github.com/yorkie-team/codepair/issues/196#issuecomment-1200537556).

**Why**:
Some types are broken.
Maybe you can stop supporting legacy browsers, or you can add a legacy types for backward compatibility.

**Comment by blurfx** [comment]
@gollumnima Your issue has been moved here from #196.

**Comment by gollumnima** [comment]
Thank you!

**Comment by blurfx** [comment]
Closed by #201
