### ISSUE TITLE
Only certain sentences were displayed in a different color.

### ISSUE THREAD

**Issue by chromato99** [yorkie-team/codepair#215]
**What happened**:

In sometimes, only certain sentences were displayed in a different color.

![Screenshot from 2022-08-13 21-52-59](https://user-images.githubusercontent.com/20539422/184495272-779ec4b4-93dc-4013-b3ee-5fc5433a3811.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

I don't know exactly how to reproduce this bug. However, in my local environment, when I access the link below, it keeps showing up in red(pink?) even when the window is refreshed.
https://codepair.yorkie.dev/0a4he5

However, it did not reproduce on my other computer.

**EDIT: I found how to reporduce this problem**
It seems no problem with normal typing.
But in certain cases, problems arise.
One way I've found is to type a dash once, then a single tap and then a dash, then a double tap and then a dash.

![2022-09-14-00-03-20](https://user-images.githubusercontent.com/20539422/189938204-68138542-e0cc-47c8-a876-3f8747975b00.gif)
https://codepair.yorkie.dev/n8hxvd

But if it still only happens on my desktop, I think my desktop might be the problem.

**Anything else we need to know?**:

Maybe my local environment is the problem, so if you think it's not a bug in codepair, please close it.
Or let me know if you need more information!

**Environment**:
- Operating system: Arch Linux
- Browser and version: Vivaldi 5.4.2753.28 (Stable channel) stable (64-bit)

**Comment by chromato99** [comment]
I think I found how to reproduce this issue. I edited above comment.

**Comment by easylogic** [comment]
Close the issue because the markdown style has been fixed across the board.
