### ISSUE TITLE
Support MinIO as an default storage option for image repository

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#224]
**What would you like to be added**:
Currently, the image repository only supports S3 for storage. To reduce the initial setup cost and provide more flexibility to users, it is recommended to introduce support for MinIO as an default storage option. MinIO is a lightweight object storage server that is compatible with Amazon S3 APIs.

**Why is this needed**:
By adding MinIO support, users can have the option to choose between S3 and MinIO for their image repository storage, allowing them to configure based on their specific requirements and cost considerations.

**Additional Information**:

**Comment by minai621** [comment]
I'm interested in this issue, so can I try it?
