### ISSUE TITLE
yorkie.Document initialized twice when entering document editing page

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#228]
**What happened**:

Under specific circumstances, when entering the document editing page, `yorkie.Document` is initialized twice. Initially, when accessing the document editing page from the document list, `yorkie.Client` and `yorkie.Document` are initialized once. However, upon returning to the document list and revisiting the document page, `yorkie.Document` is initialized twice.

[screen-capture.webm](https://github.com/yorkie-team/codepair/assets/2059311/662bef3c-b14f-4c00-91c4-936f5af46292)

This behavior seems to increase the frequency of race condition between `Client.Sync` and `Client.Detach`.

Related to
- https://github.com/yorkie-team/codepair/issues/220
- https://github.com/yorkie-team/yorkie-js-sdk/pull/862
- https://github.com/yorkie-team/yorkie-js-sdk/issues/856

**What you expected to happen**:

`yorkie.Document` should only be initialized once when entering the document editing page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Access the document list.
2. Enter the document editing page.
3. Return to the document list.
4. Re-access the document editing page.
5. Notice that `yorkie.Document` is initialized twice.

**Anything else we need to know?**:

**Environment**:
- Operating system:
- Browser and version:
- CodePair version:

**Comment by wet6123** [comment]
I'm intereste it. Can i try it?

**Comment by devleejb** [comment]
@wet6123 
Sure! I'll assign you.
Please share the reason and discuss here!

**Comment by devleejb** [comment]
@wet6123 Could you share the progress?

**Comment by wet6123** [comment]
@devleejb oh I was so busy finishing my school project, so I couldn't work on it. I'll wrap it up by this week!

**Comment by wet6123** [comment]
@hackerwins I'm trying to reproduce this bug, but I'm unable to reproduce it. Could you please check again, and if the bug is still there, please tell me more about your reproduction.

**Comment by devleejb** [comment]
In development mode, it runs in StrictMode. So, because of debugging purpose, the `useEffect` runs twice in developement mode.

Reference: https://sentry.io/answers/react-useeffect-running-twice/Reference: https://sentry.io/answers/react-useeffect-running-twice/
