### ISSUE TITLE
404 Not Found when trying GitHub OAuth login

### ISSUE THREAD

**Issue by minai621** [yorkie-team/codepair#234]
https://github.com/user-attachments/assets/dc6978c0-5cc8-4801-a596-0deb045158d0

**What happened**:
A network error occurred while attempting to log in, and now every subsequent login attempt results in a 404 Not Found error.

When trying to log in in the development environment, the login works correctly.
It is suspected that the network error prevented user information from being saved, causing the usersService.findOrCreate to fail to find user information, leading to the 404 Not Found error.

**What you expected to happen**:
I expected the login process to complete successfully without encountering a 404 Not Found error.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to log in using GitHub OAuth.
Experience a network error during the login attempt.
Try logging in again and observe the 404 Not Found error at the GET /auth/callback endpoint.

**Anything else we need to know?**: None.

**Environment**:
- Operating system: MacOS Sonoma 14.4.1
- Browser and version: Arc 1.51.0
- CodePair version: v0.4.27

**Environment Update 24.07.13, 22:19 **:
The same issue occurs when tested on chrome.
- Browser and version:  Chrome 126.0.6478.127(arm64)

**Comment by devleejb** [comment]
Related to https://github.com/yorkie-team/codepair/issues/209

**Comment by devleejb** [comment]
The cause of this problem is https://github.com/yorkie-team/codepair/issues/209.
