### ISSUE TITLE
Update GetDocuments API request specification in CodePair to match recent changes in Admin Server

### ISSUE THREAD

**Issue by kokodak** [yorkie-team/codepair#240]
**Description**:

Recently, the request specification for the GetDocuments API in Admin Server has changed through [this PR](https://github.com/yorkie-team/yorkie/pull/931).

As a result, the parts of CodePair that utilize the GetDocuments API need to be updated to align with the new API request specification.

https://github.com/yorkie-team/codepair/blob/e1cebe0ec3304b2ad8cdad94926a25fadef39da3/backend/src/workspace-documents/workspace-documents.service.ts#L165-L176

**Why**:

To ensure seamless integration between CodePair and Admin Server after the recent change in the API request specification. This enhancement is crucial to maintain the functionality of CodePair.

**Comment by devleejb** [comment]
@kokodak
If you want to resolve this issue, please tell me.
I will assign you.

**Comment by kokodak** [comment]
> @kokodak If you want to resolve this issue, please tell me. I will assign you.

I want to resolve it. Could I try it?
