### ISSUE TITLE
Issue with `updatedAt` field showing incorrect values in document list

### ISSUE THREAD

**Issue by blurfx** [yorkie-team/codepair#253]
**What happened**:

There is an issue with the `updatedAt` of a document showing another document `updatedAt`. Specifically, the `updatedAt` in the document list is being reversed and reflecting a different document's value.

This issue occurs during the bulk retrieval of document lists using [this patch](https://github.com/yorkie-team/yorkie/pull/931). In this process, there is no guarantee that the order of the keys passed to the DB query matches the order of the documents in the query result.

**What you expected to happen**:
The `updatedAt` field in the document list should accurately reflect the `updatedAt` of each respective document.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use the bulk retrieval method for document lists.
2. Update some document 
3. Compare the `updatedAt` fields in the document list with the actual `updatedAt` values of the documents.

**Anything else we need to know?**:

I think this issue should be handled on the client side, because the query result(document list) from the server may not always contain all the documents of given keys.
For example, when document keys [1, 2, 3] are passed to the server and document 2 does not exist, result should be [1, 3].

**Environment**:
- Operating system:
- Browser and version:
- CodePair version: 
- Yorkie version: v0.4.28

**Comment by blurfx** [comment]
cc @raararaara

**Comment by raararaara** [comment]
To solve this issue, how about converting the result of `yorkieDocumentList` into [id, yorkieDocument] format and mapping it?

https://github.com/yorkie-team/codepair/blob/fd620433148687910c156d9e3ee209e71e8145d7/backend/src/workspace-documents/workspace-documents.service.ts#L82-L84

cc @blurfx
