### ISSUE TITLE
Add Ollama Model for Yorkie intelligence

### ISSUE THREAD

**Issue by sihyeong671** [yorkie-team/codepair#255]
**What would you like to be added**:
- Model selection by changing model name in `env` file
- Download Ollama model automatically when running codepair

**Why is this needed**:
Since Codepair is currently using OpenAI ChatGPT which costs money, so we need to add option to use ollama's model which can use freely and run locally

**Additional Information**:

**Comment by devleejb** [comment]
It seems like a good way for new users to get started without any setup. It would also be helpful to clearly list the required computer specifications.
