### ISSUE TITLE
Add Feature to Move Cursor to User's Profile when Profile is Clicked

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#256]
**Description**:
When clicking on a user's profile, add functionality to automatically move the cursor to the location in the document where that user's profile is located. This feature is commonly seen in collaboration applications like Figma.

**Why**:
In long documents where collaboration and communication are key, this feature would greatly enhance the user experience by allowing users to easily locate and interact with specific sections of the document based on the profiles of team members they are working with.

**Comment by choidabom** [comment]
I'm interested in this issue. Can I try it?

**Comment by krapie** [comment]
@choidabom Sure! I will assign you :)

**Comment by devleejb** [comment]
Refer this message: [Discord Message URL](https://discord.com/channels/928301813785038878/1192749209435259000/1271726778490032235)

**Comment by devleejb** [comment]
@choidabom Could you share the progress?
