### ISSUE TITLE
There is picture on README.md that path could not be found.

### ISSUE THREAD

**Issue by mihilt** [yorkie-team/codepair#266]
**Description**:
`screenshot.png` is disappeared from README.md.

#250
It looks file was deleted within this pull request.

The file is as follows.

<kbd><img width="896" alt="screenshot" src="https://user-images.githubusercontent.com/50368758/234290004-36aba56a-bed8-4c11-aeb2-b22f5b36f9f8.png"></kbd>

**Why**:

**Comment by easylogic** [comment]
@mihilt 

Thanks for your reporting. 

I will check it.
