### ISSUE TITLE
Integrate `YorkieIntelligence` component into `FormatBar` component

### ISSUE THREAD

**Issue by beberiche** [yorkie-team/codepair#267]
**What happened**:
Currently, there is an issue where the `yorkie-intelligence` button moves with each change when adding or removing markdown symbols to the selected text using the format bar or keyboard shortcuts.

![이슈](https://github.com/user-attachments/assets/55d4d128-d59b-460d-a09b-3aeeb95882cd)

**What you expected to happen**:
Since `YorkieIntelligence.tsx` and `FormatBar.tsx` are rendered separately, integrating them into one component can resolve this issue and potentially enhance the user experience.

**How to reproduce it (as minimally and precisely as possible)**:
There are two proposed ideas to solved this problem:

1. Inserting the `YorkieIntelligence` component into the `FormatBar` component.
2. Creating a fixed navigation bar at the top of the `Editor` area and incorporating both the `FormatBar` and `YorkieIntelligence` components. This approach might increase the workload but could offer added convenience for users by including other markdown features like `h1, h2, h3`, `Image`, `Link`, etc.

Please consider which option would be more suitable and provide your insights.

**Comment by beberiche** [comment]
I'll try it :)

**Comment by devleejb** [comment]
@beberiche 
Sure! I'll assign you.
