### ISSUE TITLE
Text formatting duplication and heading preservation issues in markdown

### ISSUE THREAD

**Issue by choidabom** [yorkie-team/codepair#268]
**What happened**:
There are two main issues related to text formatting in markdown:
1. Text formatting duplication problem: When applying the same formatting to already formatted text, it results in unnecessary duplication of formatting.
2. Heading formatting preservation problem: Applying different formatting to text that is already formatted with headings (Heading 1, 2, 3) causes the heading formatting to be unwrapped.

https://github.com/user-attachments/assets/796e9f15-ea8f-4661-9594-a2deb6fb8cf4

**What you expected to happen**:
- Text formatting should not duplicate when applying the same format to text. 
- Heading formatting should be preserved when applying bold format to text.

**Comment by devleejb** [comment]
Related to https://github.com/yorkie-team/codepair/issues/267
