### ISSUE TITLE
Bug when changing username not updating workspace name associated with original username

### ISSUE THREAD

**Issue by rappire** [yorkie-team/codepair#275]
**What happened**:
When changing the username from the original one to a different one, the workspace name associated with the original username is not updated. This results in the workspace name still reflecting the original username even after the username change. Additionally, attempting to change it back to the original username is not possible.

**What you expected to happen**:
When changing the username, the workspace name associated with the original username should also be updated to reflect the new username. Furthermore, the ability to change back to the original username should be supported.

**How to reproduce it**:
1. Create an account with a specific username.
2. Change the username to a different one.
3. Check that the workspace name remains the same as the original username.

**Anything else we need to know?**:
It is expected that when the username is changed, any workspace names associated with the original username should also be automatically updated to reflect the new username. This issue is impacting user experience, especially when users want to revert back to their original username.

ps : I want to go back to my original ID....

**Comment by rappire** [comment]
If it's not intended, I'd like to work on it.

**Comment by devleejb** [comment]
@rappire 
It is an intended feature. We keep the nickname and workspace within the same scope.
