### ISSUE TITLE
Install husky to apply lint on commits or pushes

### ISSUE THREAD

**Issue by choidabom** [yorkie-team/codepair#276]
**What would you like to be added**:
Currently, linting is not automatically applied when making commits or pushing changes for CodePair. To ensure code quality and consistency, it would be beneficial to install Husky, a tool that enables running scripts on Git hooks, to automatically apply linting when committing or pushing changes.

**Why is this needed**:
Enforcing linting standards through Husky will help maintain a clean and consistent codebase for CodePair, improving overall code quality.

**Additional Information Needed**:

**Comment by choidabom** [comment]
@devleejb Can I try it? 😀

**Comment by devleejb** [comment]
@choidabom 
Sure! I will assign you.
