### ISSUE TITLE
Consolidate `.gitignore` files for backend and frontend projects

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#279]
**What would you like to be added**:
Currently, our project has separate `.gitignore` files for the backend and frontend projects. This makes it cumbersome to manage and maintain. It would be beneficial to consolidate the common entries into a global `.gitignore` file.

**Why is this needed**:
By consolidating the `.gitignore` entries into a global file, we can streamline the management of the project and ensure consistency in ignoring unnecessary files and directories across both the backend and frontend codebases. This will simplify the development process and reduce the chances of missing important entries.

**Additional Information**:

**Comment by sihyeong671** [comment]
Can you assign this issue to me?

**Comment by devleejb** [comment]
@sihyeong671  Sure! I'll assign you!
