### ISSUE TITLE
Unable to use Export feature when accessing document via Share Link

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#287]
**What happened**:
When accessing a document via Share Link, the Export feature is not accessible. Users should be able to use the Export feature when accessing a document through a Share Link.

**What you expected to happen**:
Users should be able to use the Export feature when accessing a document via Share Link.

**How to reproduce it (as minimally and precisely as possible)**:
1. Access a document using the Share Link.
2. Attempt to use the Export feature.
3. Notice that the Export feature is not available.

**Anything else we need to know?**:

**Environment**:
- Operating system: ALL
- Browser and version: ALL
- CodePair version: v0.1.1

**Comment by choidabom** [comment]
@devleejb It seems that this issue is not currently occurring. Could you please check it?

**Comment by devleejb** [comment]
It seems that exporting from the document shared in the code will not be impossible.
