### ISSUE TITLE
Add clear comments to differentiate between Persistence and Volatile Redux Store elements

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair#352]
**What would you like to be added**:
Currently, it is challenging to distinguish which parts of our Redux Store are meant for Persistence and which ones are Volatile. While the existing comments in CodePair provide some guidance, they are not explicit enough. 

I propose that we enhance the clarity of our comments in the Redux store configuration. Here's an example of the current structure:

```typescript
const reducers = combineReducers({
	// Persistence
	auth: authSlice,
	config: configSlice,
	// Volatile
	user: userSlice,
	editor: editorSlice,
	workspace: workspaceSlice,
	document: documentSlice,
	setting: settingSlice,
});
```

We should add more descriptive comments or possibly even a dedicated section to clearly label and explain why each slice belongs to either Persistence or Volatile categories.

**Why is this needed**:
Providing clearer documentation within the code will help developers and contributors better understand the design decisions, enhance maintainability, and prevent potential confusion when working with the Redux Store.

**Additional Information**:

**Comment by devleejb** [comment]
@choidabom It might be a good idea to explicitly rename each reducer. What do you think?
For example: `authPersistenceSlice`

**Comment by choidabom** [comment]
@devleejb 
I think renaming is clear in conveying the meaning, but it may become too verbose. So let's focus on adding clear comments in the Redux store configuration. I suggest either including this in the CodePair docs or elaborating on it in the frontend design documentation.

**Comment by devleejb** [comment]
@choidabom I think that's a good idea. Instead of adding it to the docs, it would be better to include clear comments so it can be checked directly at the time of development.

**Comment by choidabom** [comment]
@devleejb I'll try this issue
