### ISSUE TITLE
Error when opening `edit page` on mobile devices such as iPhone

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#371]
**What happened**:

When trying to open CodePair `edit page` on mobile devices, such as an iPhone, an error occurs.

![AA8F1D3C-4C75-4885-B1D4-21350F8B63AE_4_5005_c](https://github.com/user-attachments/assets/dd879503-7bdd-418f-bcdd-c6615453036b)

**What you expected to happen**:

The editing screen and reading mode should be displayed properly without any errors.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open CodePair on an iPhone.
2. Attempt to access specific CodePair edit page.
3. Observe the error that occurs.

**Anything else we need to know?**:

**Environment**:
- Operating system: iOS 16.1.1
- Browser and version: Google Chrome, 130.0.6723.37
- CodePair version: v0.1.15

**Comment by devleejb** [comment]
@hackerwins 
CodePair’s edit page works well on my iPhone (in both Safari and Chrome).
Could you share the details of your environment?

**Comment by hackerwins** [comment]
When I check the console error on my iPhone, I get the following error:

<img width="947" alt="Screenshot 2024-10-26 at 1 15 03 AM" src="https://github.com/user-attachments/assets/b1017369-27eb-439f-ba32-4c529150d332">
<img width="541" alt="Screenshot 2024-10-26 at 1 15 58 AM" src="https://github.com/user-attachments/assets/ee7a128f-573f-46bb-a7b0-6e89cec17770">

**Comment by hackerwins** [comment]
I updated iOS on my iPhone.
