### ISSUE TITLE
Ensure Client.Deactivate on browser close for better GC

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#401]
**What would you like to be added**:

CodePair editor uses [`yorkie.Text`](https://yorkie.dev/docs/js-sdk#text), and during recent performance tests, we observed that as the amount of editing increases, the response time for `PushPullChanges` becomes slower. This issue was analyzed, revealing that `yorkie.Text`, based on RGA, has tombstones to execute simultaneously occurring operations. Even if content is deleted from editor, the tombstones occupy space, and while Yorkie implements [GC mechanism](https://github.com/yorkie-team/yorkie/blob/main/design/garbage-collection.md) to manage this, the effectiveness of GC relies on detaching clients that are no longer editing.

To ensure more effective GC, we need to guarantee the execution of `Client.Deactivate` upon browser closure. Since browser termination may happen unexpectedly, I suggest utilizing [`navigator.sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) or [`fetch() with the keepalive`](https://developer.mozilla.org/en-US/docs/Web/API/RequestInit#keepalive) option to implement this.

For reference, see the discussion about sending HTTP requests on page exit: [Reliably Send an HTTP Request as a User Leaves a Page](https://css-tricks.com/send-an-http-request-on-page-exit/)

**Why is this needed**:

**Additional Information**:

**Comment by devleejb** [comment]
I’m not sure I fully understand. 
Are you suggesting that `client.deactivate` should be translated into a REST API call using `fetch()` or `sendBeacon`? 

Could you provide more explanation?

**Comment by devleejb** [comment]
Related to https://github.com/yorkie-team/yorkie-js-sdk/pull/928.
