### ISSUE TITLE
Improving the drawing board

### ISSUE THREAD

**Issue by hackerwins** [yorkie-team/codepair#65]
**Description**:

We added basic features, line drawing and an eraser to the drawing board.
We need to add features such as line style or shapes so that users can draw more various content.

I think it will be helpful to refer to the UI of [Jamboard](https://jamboard.google.com/) or [Zoom's annotation tool](https://support.zoom.us/hc/en-us/articles/115005706806-Using-annotation-tools-on-a-shared-screen-or-whiteboard).

<img width="400" alt="Screen Shot 2021-03-15 at 9 45 19" src="https://user-images.githubusercontent.com/2059311/111090559-7ecc8d00-8573-11eb-8626-42bd1424ba04.png">

**Why**:

Users can draw various contents on the drawing board.

**Comment by hackerwins** [comment]
Let's add more colors and styles of the brush.

**Comment by ppeeou** [comment]
@hackerwins 
I'm going to close this issue after providing the two functions below. Would it be okay??

- [ ] Adjust the shape size
- [ ] Provides text function

**Comment by easylogic** [comment]
We are supporting tldraw. 
Close the issue.
